### ISSUE TITLE
Templating type error in first task (Ansible 2.1.1)

### ISSUE THREAD

**Issue by ageis** [nusenu/ansible-relayor#73] opened 2016-08-17 10:48 UTC
```TASK [ansible-relayor : setup IP list (1/2)] ***********************************
fatal: [tor-relay]: FAILED! => {"failed": true, "msg": "{{ v6tmp[0:ipv4_count|int]|ipv6('address') }}: Unexpected templating type error occurred on ({{ v6tmp[0:ipv4_count|int]|ipv6('address') }}): 'bool' object has no attribute '__getitem__'"}```

This is because `tor_v6ips` is empty (and thus evaluates to `False`), but it is not listed as a required role variable in the README, and the value of `tor_IPv6` does not affect this task.

**Comment by nusenu** [comment] 2016-08-17 12:11
This is a known regression in ansible 2.x's IPv6 filter and the reason we state ansible <v2.0 as a requirement of this role:
https://github.com/nusenu/ansible-relayor#requirements

Once ansible fixes this regression we will update the requirements section to no longer require ansible 1.9.

See also:
https://github.com/nusenu/ansible-relayor/issues/56
https://github.com/ansible/ansible/issues/14829
https://bugzilla.redhat.com/show_bug.cgi?id=1364732
https://groups.google.com/d/msg/ansible-devel/gks0D9n49C8/ND6l5t7kAwAJ

**Comment by ageis** [comment] 2016-08-17 12:19
@nusenu Got it. Some general feedback: This is the best Tor relay Ansible role out there, but it's a bit of a mess in some aspects IMO. I am debating writing my own role that is much simpler, less options, doesn't use OfflineMasterKey, and targets only Debian-based systems, for a project for [Library Freedom Project](https://libraryfreedomproject.org/) (a non-profit which encourages libraries to run relays). But I'd also like to help you improve this, make the YAML more readable, make it Ansible v2 compatible, etc. Don't be surprised if you see a couple PRs from me. Thanks for maintaining this.

**Comment by nusenu** [comment] 2016-08-17 13:05
duplicate of #56 
(regarding the other points: I covered them in an email)

**Closed by nusenu** 2016-08-17 13:05 UTC
